### ISSUE TITLE
Tests fail if "prove" is not the expected one

### ISSUE THREAD

**Issue by eserte** [maxmind/TAP-Formatter-TeamCity#2]
There are quite many fail reports, see http://matrix.cpantesters.org/?dist=TAP-Formatter-TeamCity%200.08

I think the problem is that the "prove" binary used in t/basic.t is in these cases /usr/bin/prove belonging to the system perl, and not the prove belonging to the currently active perl (the usual case for a manually compiled perl without perlbrew). This could be fixed by prepending `$Config::Config{scriptdir}` to `$ENV{PATH}` in the test script.

Another problem is that the prove filename may be have a perl version appended (that is, something like `/opt/perl-5.23.6/bin/prove5.23.6`), especially for bleadperl. So probably you have to check first if there's a `"prove$Config::Config{version}"` in the PATH and pick this one.

**Comment by oschwald** [comment]
Closing as this module is no longer being developed.
