### ISSUE TITLE
If a test file runs a test with the same name as the file this is turned into a failure

### ISSUE THREAD

**Issue by autarch** [maxmind/TAP-Formatter-TeamCity#3]
TAP::Formatter::TeamCity has code trying to detect tests exiting prematurely. That's great!

However, that code has a couple of corner cases that might cause tests to be reported as failed even though they ran and passed just fine.

In particular, if the description of the first test equals the name of the test file running, our formatter will wrongly report the test as having failed. The following test file will trigger this issue when saved as t/foo.t and run with the custom TAP formatter:

```
use strict;
use warnings;
use Test::More;
pass('t/foo.t');
done_testing;
```

prove without the custom formatter will be entirely happy with the output.

**Comment by autarch** [comment]
I looked at this a little closer. I think the issue is that the same code that is used to finish a TC suite when a subtest is run is also used to finish the "main" suite (the suite for the .t file itself). Though for TC these cases are identical (suites are suites), from the TAP perspective a file is not the same as a subtest.

I think that ideally we'd detect file exit by looking at an exit code, but I'm not sure if the TAP harness formatter system makes that available.

This all might be much simpler once Test2 is stable and we don't actually have to parse TAP.

**Comment by oschwald** [comment]
Closing as we no longer use or develop this module.
