### ISSUE TITLE
Can't install module from cpan 

### ISSUE THREAD

**Issue by hurricup** [maxmind/TAP-Formatter-TeamCity#8]
Getting a lot of failed tests. Tried with 24.4 and 26.

**Comment by oschwald** [comment]
This package does not work with `Test2`. You would have to downgrade `Test::Simple` to 1.001014 or earlier to use this.

**Comment by hurricup** [comment]
Dam. I was planning to use it in my perl plugin for Jetbrains IDEs. And I can't demand this from users.
Are there some unsolvable problems? Not dived in yet.

**Comment by oschwald** [comment]
This module doesn't cope with the changed TAP formatting that came with `Test2`. I suspect it wouldn't be terribly hard to get it working, but we are replacing our use with a new formatter that uses the `Test2` events directly. There is an older version of this new module at https://github.com/maxmind/Test2-TeamCity, but that is missing some of our internal changes. I am not sure when we are planning on pushing those or releasing to CPAN.

**Comment by hurricup** [comment]
Thank you. I'll investigate this.

**Comment by hurricup** [comment]
Ok, i've implemented working version https://github.com/Camelcade/TAP-Formatter-Camelcade
Unsure it's usable on the TeamCity but serves my purpose well. 
Thank you for your code, helped a lot :)
